# Generated by Django 3.2.4 on 2021-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_contact', '0003_contact_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Link')),
                ('title', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=256)),
                ('publish', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
