# Generated by Django 3.2.4 on 2021-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_contact', '0005_scrape_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='In Stock'),
        ),
    ]
