# Generated by Django 3.2.4 on 2021-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_contact', '0006_scrape_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrape',
        ),
    ]
