# Generated by Django 3.2.4 on 2021-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
