# Generated by Django 3.2.4 on 2021-06-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0007_auto_20210615_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obeid_projects.customer'),
        ),
    ]
