# Generated by Django 3.2.4 on 2021-06-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0012_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
