# Generated by Django 3.2.4 on 2021-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0015_auto_20210615_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
