# Generated by Django 3.2.4 on 2021-06-25 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0030_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
