# Generated by Django 3.2.4 on 2021-06-25 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0034_alter_project_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='datetime',
            new_name='create',
        ),
        migrations.AddField(
            model_name='project',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
