# Generated by Django 3.2.4 on 2021-06-25 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0036_auto_20210625_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
