# Generated by Django 3.2.4 on 2021-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0037_auto_20210625_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='publish',
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(help_text='Name + Lastname', max_length=128, unique=True),
        ),
    ]
