# Generated by Django 3.2.4 on 2021-07-11 22:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('obeid_projects', '0039_alter_project_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
